# TASK-001B schematic + exact part database verified Bank35 nominal 3.3V.
# P1 fourteen data pins, P2 two data pins plus three LED-loaded outputs.
set_property PACKAGE_PIN A20 [get_ports {serial_data[0]}]
set_property PACKAGE_PIN H16 [get_ports {serial_data[1]}]
set_property PACKAGE_PIN B19 [get_ports {serial_data[2]}]
set_property PACKAGE_PIN B20 [get_ports {serial_data[3]}]
set_property PACKAGE_PIN C20 [get_ports {serial_data[4]}]
set_property PACKAGE_PIN H17 [get_ports {serial_data[5]}]
set_property PACKAGE_PIN D20 [get_ports {serial_data[6]}]
set_property PACKAGE_PIN D18 [get_ports {serial_data[7]}]
set_property PACKAGE_PIN H18 [get_ports {serial_data[8]}]
set_property PACKAGE_PIN D19 [get_ports {serial_data[9]}]
set_property PACKAGE_PIN F20 [get_ports {serial_data[10]}]
set_property PACKAGE_PIN E19 [get_ports {serial_data[11]}]
set_property PACKAGE_PIN F19 [get_ports {serial_data[12]}]
set_property PACKAGE_PIN K17 [get_ports {serial_data[13]}]
set_property PACKAGE_PIN G20 [get_ports {serial_data[14]}]
set_property PACKAGE_PIN J18 [get_ports {serial_data[15]}]
set_property PACKAGE_PIN H20 [get_ports shift_clock]
set_property PACKAGE_PIN J20 [get_ports latch_clock]
set_property PACKAGE_PIN L19 [get_ports output_disable]
set_property IOSTANDARD LVCMOS33 [get_ports {serial_data[*] shift_clock latch_clock output_disable}]
set_property DRIVE 4 [get_ports {serial_data[*] shift_clock latch_clock output_disable}]
set_property SLEW SLOW [get_ports {serial_data[*] shift_clock latch_clock output_disable}]
# Conservative 5ns/0.5ns FPGA pin output budgets; external skew is separately estimated.
set_output_delay -clock forwarded50 -max 5.000 [get_ports {serial_data[*] shift_clock latch_clock output_disable}]
set_output_delay -clock forwarded50 -min 0.500 [get_ports {serial_data[*] shift_clock latch_clock output_disable}]
